source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'sqlite3'
gem 'rabl'
gem 'oj'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-coolline'
end